### ISSUE TITLE
SimpleCookie in Python3 也会丢失顺序

### ISSUE THREAD

**Issue by neargle** [aploium/my_utils#1]
https://github.com/aploium/my_utils/blob/ff4daf8057c3edd4d41230240a029289e3ce0023/http_clay.py#L417

![image](https://user-images.githubusercontent.com/7868679/31427670-a8ac93f2-ae2d-11e7-9430-1f706370f0db.png)

**Comment by aploium** [comment]
谢谢:)  其实之前就发现了
在py3.6下不会丢失顺序, 而在3.5及以前会丢
这是因为在3.6下有一项更新, 让所有kwargs的顺序得以保留

https://docs.python.org/3/whatsnew/3.6.html#pep-468-preserving-keyword-argument-order
`**kwargs in a function signature is now guaranteed to be an insertion-order-preserving mapping.`

其实在很久以前就已经修复了, 如果有需要的话可以用这个代替
https://github.com/aploium/my_utils/tree/master/requestfuzz
ps: http_clay已经作为一小部分功能整合进requestfuzz了
这个顺序问题也已经修复

以及我很好奇......你是怎么发现这个疙瘩角的自用玩意的

**Comment by neargle** [comment]
感谢回复。受教！之后我拜读一下requestfuzz的源码。

最初发现这个项目是在 github 首页的 timeline 上。一年前学习flask源码挖掘漏洞的时候，稍微读了一下 zmirror 的源码，对你的编码规范以及项目的设计和管理非常服气，所以这种以 "my_utils" 为名的项目自然对我来说有很大的吸引力。我在 rss 上订阅了项目的commit， 有新 commit 就 pull 下来看一下docstring 和 测试代码，有时间的时候再回来看看源码。

**Comment by aploium** [comment]
qwq给大佬献上膝盖  我不觉得zmirror有哪写得好的。。各种抽象和封装都很烂  
requestfuzz在渗透工具的开发中应该能起到一些作用，用于对http请求进行解析，修改(污染)和重放(抱歉因为不是正式项目所以没文档。。感兴趣的话可以看看注释)
